### ISSUE TITLE
No clue

### ISSUE THREAD

**Issue by glenaeguidry** [yanamal/html-hax#34] opened 2018-03-20 21:38 UTC
The last puzzle had no good clue.

**Comment by yanamal** [comment] 2018-03-22 04:27
Fixed by https://github.com/yanamal/html-hax/pull/35

**Closed by yanamal** 2018-03-22 04:27 UTC

**Comment by yanamal** [comment] 2018-03-22 04:30
Also, this was a duplicate of https://github.com/yanamal/html-hax/issues/31
